[[ServerList]]
  ID = 1
  Label = "AB Supercenter"
  URL = "autobodysupercenter.com"
  Install = "absupercenter"
  Protocol = "https://"

[[ServerList]]
  ID = 2
  Label = "ACS Steel"
  URL = "acssteel.com"
  Install = "acssteel"
  Protocol = "https://"

[[ServerList]]
  ID = 3
  Label = "Aero Repair"
  URL = "www.aerocomponentrepair.com"
  Install = "aerorepair"
  Protocol = "https://"

[[ServerList]]
    ID = 4
    Label = "Aguirrie"
    URL = "aguirrie.com"
    Install = "aguirrie"
    Protocol = "https://"

[[ServerList]]
    ID = 5
    Label = "American Bank of Oklahoma"
    URL = "www.americanbankok.com"
    Install = "americanbankok"
    Protocol = "https://"

[[ServerList]]
    ID = 6
    Label = "Autobody Website"
    URL = "matrixautobody.com"
    Install = "autobodysites"
    Protocol = "https://"

[[ServerList]]
    ID = 7
    Label = "Matrix Autobody"
    URL = "matrixautobody.com"
    Install = "autobodysites"
    Protocol = "https://"

[[ServerList]]
    ID = 8
    Label = "Ultimate CRC"
    URL = "ultimatecrc.com"
    Install = "autobodysites"
    Protocol = "https://"

[[ServerList]]
    ID = 9
    Label = "Barry Electric"
    URL = "barryelectric.com"
    Install = "barryelec"
    Protocol = "https://"

[[ServerList]]
    ID = 10
    Label = "GOBEC"
    URL = "gobec.net"
    Install = "barryelec"
    Protocol = "https://"

[[ServerList]]
    ID = 11
    Label = "Barry Electric - Landing Page"
    URL = "landing.barryelectric.com"
    Install = "barryelec"
    Protocol = "https://"

[[ServerList]]
    ID = 12
    Label = "Blessing Gravel"
    URL = "blessinggravel.com"
    Install = "blessinggravel"
    Protocol = "https://"

[[ServerList]]
    ID = 13
    Label = "Blessing Sports Surface"
    URL = "blessingsportssurfaces.com"
    Install = "blessinggravel"
    Protocol = "https://"

[[ServerList]]
    ID = 14
    Label = "bugRight"
    URL = "bugright.com"
    Install = "bugright"
    Protocol = "https://"

[[ServerList]]
    ID = 15
    Label = "Quality Bumper of DFW"
    URL = "qualitybumperofdfw.com"
    Install = "bumperworlddfw"
    Protocol = "https://"

[[ServerList]]
    ID = 16
    Label = "CAC Claremore"
    URL = "cacclaremore.org"
    Install = "cacclaremore"
    Protocol = "https://"

[[ServerList]]
    ID = 17
    Label = "Carlson Company"
    URL = "carlson-company.com"
    Install = "carlsonco"
    Protocol = "https://"

[[ServerList]]
    ID = 18
    Label = "Claremore Appliance"
    URL = "claremoreappliancerepair.com"
    Install = "claremoreappl"
    Protocol = "https://"

[[ServerList]]
    ID = 19
    Label = "Classic Golf Cart"
    URL = "classicgolfcarts.com"
    Install = "classicgolf"
    Protocol = "https://"

[[ServerList]]
    ID = 20
    Label = "Classic Golf Cart"
    URL = "classicgolfcarts.com"
    Install = "classicgolf"
    Protocol = "https://"

[[ServerList]]
    ID = 21
    Label = "Advance Auto Car"
    URL = "advanceautocar.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 22
    Label = "CW2"
    URL = "autobodywebsite.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 23
    Label = "B&B Autobody"
    URL = "bandbautobody.net"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 24
    Label = "Bedford Autobody"
    URL = "bedfordautobody.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 25
    Label = "Body Shop Waco"
    URL = "bodyshopwaco.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 26
    Label = "Brinks Autobody"
    URL = "brinksautobody.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 27
    Label = "Central Collision"
    URL = "central-collision.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 28
    Label = "Cliffords Custom Collision"
    URL = "cliffordscustomcollision.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 29
    Label = "Combs Collision Inc"
    URL = "combscollisioninc.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 30
    Label = "Custom Auto Inc"
    URL = "customautoinc.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 31
    Label = "Drive Five Star Collision"
    URL = "drivefivestarcollision.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 32
    Label = "Eddies Body Shop"
    URL = "eddiesbodyshop.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 33
    Label = "CW2"
    URL = "extremecollisionrepair.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 34
    Label = "JJ Autobody Houston"
    URL = "jjautobodyhouston.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 35
    Label = "Legendary Looks"
    URL = "legendarylooks.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 36
    Label = "Mcelwain Bros"
    URL = "mcelwainbros.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 37
    Label = "Modern Collision Center"
    URL = "moderncollisionctr.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 38
    Label = "Preferred Body Shop"
    URL = "preferredbodyshop.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 39
    Label = "Russell Barnet Collision Center"
    URL = "russellbarnettcollisioncenter.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 40
    Label = "Secrc"
    URL = "secrc.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 41
    Label = "Spriggs Auto Clinic"
    URL = "spriggsautoclinic.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 42
    Label = "Walter Jay Collision"
    URL = "walterjaycollision.com"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 43
    Label = "X Roads Collision"
    URL = "xroadscollision.net"
    Install = "collisionsite"
    Protocol = "https://"

[[ServerList]]
    ID = 44
    Label = "Custofab"
    URL = "custofab.com"
    Install = "custofab"
    Protocol = "https://"

[[ServerList]]
    ID = 46
    Label = "AG Collision Center"
    Install = "cw3"
    Protocol = "https://"
    URL = "agcollisioncenter.com"

[[ServerList]]
    ID = 47
    Label = "All Pro Auto Collision"
    Install = "cw3"
    Protocol = "https://"
    URL = "allproautocollision.com"

[[ServerList]]
    ID = 48
    Label = "Berlis Body"
    Install = "cw3"
    Protocol = "https://"
    URL = "berlisbody.com"

[[ServerList]]
    ID = 49
    Label = "Bob Russell Auto"
    Install = "cw3"
    Protocol = "https://"
    URL = "bobrussellauto.com"

[[ServerList]]
    ID = 50
    Label = "Branning Collision Centers"
    Install = "cw3"
    Protocol = "https://"
    URL = "branningcollisioncenters.com"

[[ServerList]]
    ID = 51
    Label = "Collision Tech Inc"
    Install = "cw3"
    Protocol = "https://"
    URL = "collisiontech-inc.com"

[[ServerList]]
    ID = 53
    Label = "CW3"
    Install = "cw3"
    Protocol = "https://"
    URL = "collisionwebsites.com"

[[ServerList]]
    ID = 58
    Label = "Fancy Auto Body"
    Install = "cw3"
    Protocol = "https://"
    URL = "fancyautobody.com"

[[ServerList]]
    ID = 60
    Label = "NCC Paint and Body"
    Install = "cw3"
    Protocol = "https://"
    URL = "nccpaintandbody.com"

[[ServerList]]
    ID = 61
    Label = "Rainier Collision Center"
    Install = "cw3"
    Protocol = "https://"
    URL = "rainiercollisioncenter.com"

[[ServerList]]
    ID = 63
    Label = "Rusty Wallis Collision Center"
    Install = "cw3"
    Protocol = "https://"
    URL = "rustywalliscollisioncenter.com"

[[ServerList]]
    ID = 64
    Label = "Straub Collision"
    Install = "cw3"
    Protocol = "http://"
    URL = "straubcollision.com"

[[ServerList]]
    ID = 65
    Label = "Torres Autobody and Custom Painting"
    Install = "cw3"
    Protocol = "https://"
    URL = "torresautobodyandcustompainting.com"

[[ServerList]]
    ID = 66
    Label = "DD Autobody"
    Install = "ddautobody"
    Protocol = "https://"
    URL = "ddautobodyinc.com"

[[ServerList]]
    ID = 67
    Label = "Diamond Attachments"
    Install = "diamondattach"
    Protocol = "https://"
    URL = "diamondattachments.com"

[[ServerList]]
    ID = 68
    Label = "DMI International"
    Install = "dmiintl"
    Protocol = "https://"
    URL = "www.dmiinternational.com"

[[ServerList]]
    ID = 69
    Label = "Driven Digital"
    Install = "driven4"
    Protocol = "https://"
    URL = "drivendigital.us"

[[ServerList]]
    ID = 70
    Label = "Eason Collision"
    Install = "eason"
    Protocol = "https://"
    URL = "easoncollision.com"

[[ServerList]]
    ID = 71
    Label = "Emco Industrial"
    Install = "emco"
    Protocol = "https://"
    URL = "emcoind.com"

[[ServerList]]
    ID = 72
    Label = "Fropane"
    Install = "froman"
    Protocol = "https://"
    URL = "fropane.com"

[[ServerList]]
    ID = 73
    Label = "GAP Roofing"
    Install = "gaproofing"
    Protocol = "https://"
    URL = "gaproofing.us"

[[ServerList]]
    ID = 74
    Label = "GCCS"
    Install = "gccs"
    Protocol = "https://"
    URL = "greencountrycompressors.com"

[[ServerList]]
    ID = 75
    Label = "GMMA"
    Install = "gmma"
    Protocol = "https://"
    URL = "gmma.wpengine.com"

[[ServerList]]
    ID = 76
    Label = "Approved Marine"
    Install = "hhdealer"
    Protocol = "https://"
    URL = "approvedmarine.com"

[[ServerList]]
    ID = 77
    Label = "Float Your Boat Carolinas"
    Install = "hhdealer"
    Protocol = "https://"
    URL = "floatyourboatcarolinas.com"

[[ServerList]]
    ID = 78
    Label = "HydroHoist Alabama"
    Install = "hhdealer"
    Protocol = "https://"
    URL = "hydrohoistalabama.com"

[[ServerList]]
    ID = 79
    Label = "HydroHoist Dealers"
    Install = "hhdealer"
    Protocol = "https://"
    URL = "hydrohoistdealers.com"

[[ServerList]]
    ID = 80
    Label = "HydroHoist of the Carolinas"
    Install = "hhdealer"
    Protocol = "https://"
    URL = "hydrohoistofthecarolinas.com"

[[ServerList]]
    ID = 81
    Label = "Home of Hope"
    Install = "hhdealer"
    Protocol = "http://"
    URL = "homeofhope.com"

[[ServerList]]
    ID = 82
    Label = "JCL Risk"
    Install = "jcl"
    Protocol = "https://"
    URL = "jclrisk.com"

[[ServerList]]
    ID = 83
    Label = "JCL Safety"
    Install = "jcl"
    Protocol = "https://"
    URL = "jclsafety.com"

[[ServerList]]
    ID = 84
    Label = "JCL"
    Install = "jcl"
    Protocol = "https://"
    URL = "jclsc.com"

[[ServerList]]
    ID = 85
    Label = "Jet Tank"
    Install = "jettank"
    Protocol = "https://"
    URL = "tankrepairservices.com"

[[ServerList]]
    ID = 86
    Label = "Jodeo UTV Racks"
    Install = "jodeo"
    Protocol = "https://"
    URL = "jodeoutvracks.com"

[[ServerList]]
    ID = 87
    Label = "K&B Machining"
    Install = "kandb"
    Protocol = "https://"
    URL = "k-bmachining.com"

[[ServerList]]
    ID = 88
    Label = "KT Plastics"
    Install = "ktplasticscopy"
    Protocol = "https://"
    URL = "ktplastics.com"

[[ServerList]]
    ID = 89
    Label = "Symmtek"
    Install = "ktplasticscopy"
    Protocol = "https://"
    URL = "symmtek.com"

[[ServerList]]
    ID = 90
    Label = "Laser Specialties"
    Install = "ktplasticscopy"
    Protocol = "https://"
    URL = "laserspecialties.com"

[[ServerList]]
    ID = 91
    Label = "Lake Cities Dental"
    Install = "ktplasticscopy"
    Protocol = "https://"
    URL = "lakecitiesdental.com"

[[ServerList]]
    ID = 92
    Label = "Live Wire Electric"
    Install = "livewiretx"
    Protocol = "https://"
    URL = "livewireelectrictx.com"

[[ServerList]]
    ID = 93
    Label = "Map My Region"
    Install = "mapmyregion"
    Protocol = "https://"
    URL = "mapmyregion.com"

[[ServerList]]
    ID = 94
    Label = "Ma Systems"
    Install = "masystemsdev"
    Protocol = "https://"
    URL = "masystemsdev.wpengine.com"

[[ServerList]]
    ID = 95
    Label = "Driven Digital Training"
    Install = "mfgtraining"
    Protocol = "https://"
    URL = "drivendigitaltraining.com"

[[ServerList]]
    ID = 96
    Label = "Mfg Websites"
    Install = "mfgwebsites"
    Protocol = "https://"
    URL = "mfgwebsites.com"

[[ServerList]]
    ID = 97
    Label = "3C Feeders"
    Install = "mfgwebsitesdev"
    Protocol = "https://"
    URL = "3cfeeders.com"

[[ServerList]]
    ID = 98
    Label = "Move More Steel"
    Install = "moremoresteel"
    Protocol = "https://"
    URL = "movemoresteel.wpengine.com"

[[ServerList]]
    ID = 99
    Label = "Arcboss"
    Install = "mustangmfg"
    Protocol = "https://"
    URL = "arcboss.com"

[[ServerList]]
    ID = 100
    Label = "NitroLift"
    Install = "nitrolift"
    Protocol = "https://"
    URL = "nitrolift.wpengine.com"

[[ServerList]]
    ID = 101
    Label = "NS Flame Spray"
    Install = "nsflamespray"
    Protocol = "https://"
    URL = "nsflamespray.com"

[[ServerList]]
    ID = 102
    Label = "NS Aero LLC"
    Install = "nsflamespray"
    Protocol = "https://"
    URL = "nsaerollc.com"

[[ServerList]]
    ID = 103
    Label = "COHPS"
    Install = "probonopublico"
    Protocol = "https://"
    URL = "cohps.website"

[[ServerList]]
    ID = 104
    Label = "Research Plastic"
    Install = "resplastic"
    Protocol = "https://"
    URL = "researchplastic.com"

[[ServerList]]
    ID = 105
    Label = "Rogers County Election Board"
    Install = "rogerscntyelec"
    Protocol = "https://"
    URL = "rogerscountyelectionboard.org"

[[ServerList]]
    ID = 106
    Label = "Owasso Drug"
    Install = "route66rx"
    Protocol = "https://"
    URL = "owassodrug.com"

[[ServerList]]
    ID = 107
    Label = "Route 66 Rx"
    Install = "route66rx"
    Protocol = "https://"
    URL = "route66rx.com"

[[ServerList]]
    ID = 108
    Label = "Swan Dairy"
    Install = "swandairy"
    Protocol = "https://"
    URL = "swandairy.com"

[[ServerList]]
    ID = 109
    Label = "Tank & Fuel Solutions"
    Install = "tankandfuel"
    Protocol = "https://"
    URL = "tankandfuelsolutions.com"

[[ServerList]]
    ID = 110
    Label = "Tilton Body Works"
    Install = "tiltonbody"
    Protocol = "http://"
    URL = "www.tiltonbodyworks.com"

[[ServerList]]
    ID = 111
    Label = "TRP International"
    Install = "trpintl"
    Protocol = "https://"
    URL = "trpintl.wpengine.com"

[[ServerList]]
    ID = 112
    Label = "Wenzel Site"
    Install = "wenzelsite"
    Protocol = "https://"
    URL = "wenzelsite.com"

[[ServerList]]
    ID = 113
    Label = "Tulsa Foam"
    Install = "westconst"
    Protocol = "https://"
    URL = "tulsafoam.com"

[[ServerList]]
    ID = 114
    Label = "Windor"
    Install = "windorsite"
    Protocol = "https://"
    URL = "www.windor.com"

