[[UserList]]
email = "jordan@drivendigital.us"
nicename = "Jordan Knott"
enabled = true

[[UserList]]
email = "david@drivendigital.us"
nicename = "David Moore"
enabled = true

[[UserList]]
email = "julia@drivendigital.us"
nicename = "Julia Fischer"
enabled = true

[[UserList]]
email = "shib@drivendigital.us"
nicename = "Julia Fischer"
enabled = true
